version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: cmp
      POSTGRES_PASSWORD: cmp
      POSTGRES_DB: cmp_dev
    ports: ["5432:5432"]
  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - "5672:5672"      # AMQP broker
      - "15672:15672"    # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  grafana:
    image: grafana/grafana:10.3.1
    env_file: .env
    environment:
      GF_SECURITY_ALLOW_EMBEDDING: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_NAME: "Main Org."
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Viewer"
    ports:
      - "3000:3000"
    volumes:
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro