version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER:-cmp}
      POSTGRES_PASSWORD: ${DB_PASS:-cmp}
      POSTGRES_DB: ${DB_NAME:-cmp_dev}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-cmp} -d ${DB_NAME:-cmp_dev}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - cmp_network

  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"
      - "${RABBITMQ_MANAGE_PORT:-15672}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-guest}
    restart: unless-stopped
    networks:
      - cmp_network

  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - cmp_network

  grafana:
    image: grafana/grafana:10.3.1
    env_file: .env
    environment:
      GF_SECURITY_ALLOW_EMBEDDING: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_NAME: "Main Org."
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Viewer"
      GF_SERVER_ROOT_URL: "%(protocol)s://%(domain)s:%(http_port)s/grafana" # Crucial for subpath proxying
    # ports: # REMOVE direct port exposure, access via ingress
    #   - "3000:3000"
    volumes:
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - cmp_network

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: sh -c "poetry run alembic upgrade head && poetry run uvicorn cmp_core.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./backend:/app
      - pulumi_state_data:/pulumi_state
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+asyncpg://${DB_USER:-cmp}:${DB_PASS:-cmp}@db:${DB_PORT:-5432}/${DB_NAME:-cmp_dev}
      CELERY_BROKER_URL: amqp://${RABBITMQ_USER:-guest}:${RABBITMQ_PASS:-guest}@rabbitmq:${RABBITMQ_PORT:-5672}//
      REDIS_CACHE_URL: redis://redis:${REDIS_PORT:-6379}/0
      PULUMI_BACKEND_URL: file:///pulumi_state
      GRAFANA_BASE_URL: http://localhost/grafana
      CORS_ORIGINS: ${CORS_ORIGINS:-["http://localhost:5173","http://localhost"]}

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - cmp_network

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: sh -c "poetry run celery -A cmp_core.celery_app:celery_app worker --loglevel=info -c 1"
    volumes:
      - ./backend:/app
      - pulumi_state_data:/pulumi_state
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+asyncpg://${DB_USER:-cmp}:${DB_PASS:-cmp}@db:${DB_PORT:-5432}/${DB_NAME:-cmp_dev}
      CELERY_BROKER_URL: amqp://${RABBITMQ_USER:-guest}:${RABBITMQ_PASS:-guest}@rabbitmq:${RABBITMQ_PORT:-5672}//
      REDIS_CACHE_URL: redis://redis:${REDIS_PORT:-6379}/0
      CELERY_RESULT_BACKEND: rpc://
      PULUMI_BACKEND_URL: file:///pulumi_state
      GRAFANA_BASE_URL: http://localhost/grafana 
    depends_on:
      api:
        condition: service_started
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - cmp_network

  beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: sh -c "poetry run celery -A cmp_core.celery_app:celery_app beat --loglevel=info"
    volumes:
      - ./backend:/app
      - pulumi_state_data:/pulumi_state
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+asyncpg://${DB_USER:-cmp}:${DB_PASS:-cmp}@db:${DB_PORT:-5432}/${DB_NAME:-cmp_dev}
      CELERY_BROKER_URL: amqp://${RABBITMQ_USER:-guest}:${RABBITMQ_PASS:-guest}@rabbitmq:${RABBITMQ_PORT:-5672}//
      REDIS_CACHE_URL: redis://redis:${REDIS_PORT:-6379}/0
      # ARM_CLIENT_ID, etc., are sourced from .env
      PULUMI_BACKEND_URL: file:///pulumi_state
      GRAFANA_BASE_URL: http://localhost/grafana 
    depends_on:
      api:
        condition: service_started
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - cmp_network

  frontend:
    build:
      context: ./frontend/cmp-frontend
      dockerfile: Dockerfile
      args:
          VITE_API_BASE_URL: http://localhost/api/v1
    restart: unless-stopped
    networks:
      - cmp_network

  nginx-ingress:
    image: nginx:stable-alpine
    container_name: cmp_nginx_ingress
    ports:
      - "80:80"   # Expose Nginx ingress on host port 80
    volumes:
      - ./nginx-ingress/nginx.conf:/etc/nginx/nginx.conf:ro
      # Optional: Mount logs volume
      # - ./nginx-ingress/logs:/var/log/nginx
    networks:
      - cmp_network
    depends_on:
      - frontend # Nginx should wait for the frontend service
      - api      # And the api service
      - grafana  # And the grafana service
    restart: unless-stopped

volumes:
  postgres_data:
  grafana_data:
  pulumi_state_data: {}

networks:
  cmp_network:
    driver: bridge