"""add role_id to users

Revision ID: 6ef566463c8e
Revises: 4c1c942b017b
Create Date: 2025-05-19 15:42:25.733283

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6ef566463c8e"
down_revision: Union[str, None] = "4c1c942b017b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "role_id",
            sa.Enum("admin", "devops", "viewer", name="rolename"),
            server_default="devops",
            nullable=False,
        ),
    )
    op.execute(
        "INSERT INTO roles (id) VALUES "
        "('admin'),('devops'),('viewer') "
        "ON CONFLICT (id) DO NOTHING"
    )
    op.create_foreign_key(
        None, "users", "roles", ["role_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "role_id")
    # ### end Alembic commands ###
