"""add pending to resourcestate

Revision ID: c9f902273885
Revises: 74ae5cb9a0bf
Create Date: 2025-05-20 16:29:19.575901

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c9f902273885"
down_revision: Union[str, None] = "74ae5cb9a0bf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE resourcestate ADD VALUE IF NOT EXISTS 'pending';")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
