"""add terminating to resourcestate

Revision ID: f1fbb32df71b
Revises: c9f902273885
Create Date: 2025-05-20 18:45:20.813573

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f1fbb32df71b"
down_revision: Union[str, None] = "c9f902273885"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE resourcestate ADD VALUE IF NOT EXISTS 'terminating';")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
