version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: cmp
      POSTGRES_PASSWORD: cmp
      POSTGRES_DB: cmp_dev
    ports: ["5432:5432"]
  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - "5672:5672"      # AMQP broker
      - "15672:15672"    # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest